### ISSUE TITLE
the login/signup page is not responsive

### ISSUE THREAD

**Issue by Saurav-Singh-Rauthan** [ArpitPy/whistleblower#3]
i'll fix the responsiveness of the login page
currently looks like this :
![image](https://user-images.githubusercontent.com/54982868/193395194-49529590-7d72-49a0-9d32-4d59a7730f14.png)

**Comment by yuvi2565** [comment]
@ArpitPy can you assign this issue to me

**Comment by ArpitPy** [comment]
@yuvi2565 Sure

**Comment by sanjaysargam** [comment]
Can U plz assign me too?

**Comment by somenath203** [comment]
Can you assign me this please??

**Comment by ArpitPy** [comment]
@somenath203 Assigned it to you

**Comment by Saurav-Singh-Rauthan** [comment]
hey @ArpitPy i was working on this issue...

**Comment by ArpitPy** [comment]
Oh alright @Saurav-Singh-Rauthan 
Assigned to you.

**Comment by ST1LLWATER** [comment]
Assign this to me too!

**Comment by Saurav-Singh-Rauthan** [comment]
@ArpitPy I've created a PR please check
